### ISSUE TITLE
Include babel-library-boilerplate license

### ISSUE THREAD

**Issue by jmeas** [Kflash/ES2015#1]
Hey @kflash! I'm glad you adopted the babel-library-boilerplate and modified it into your own thing, but it's an MIT licensed project, so [you'll at least need to include a copy of the original license here](https://github.com/babel/babel-library-boilerplate/blob/master/LICENSE)! Thanks!

**Comment by Kflash** [comment]
@jmeas Hi. Only thing I adopted as you call it from your boilerplate, was the gulp build task. So I don't think we can use the word *adopted*. Your project btw are from januar 2015. 
If you look into the history log of some of my previous projects, we can see that I used almost the same boilerplate as here since beginning of 2014.

Example: https://github.com/ugma/ugma/blob/master/gulpfile.js#L48-L80

Almost identical again as this boilerplate, except the build process. I used that part from your build as a test and to avoid use of es6_modules, but I'm going back to old solution.

When that is cleared. I will look into license.

**Comment by Kflash** [comment]
I switched from es6-transpillers to babel 8 days ago. The transpiller I
always used before. And your boilerplate I guess is all about babel?

Mocha mostly never used and same with sinon.

The basic code I build my first workflow with in es6 was an tutorial from
2013 from an facebook Dev on how to set up karma with different browsers.

Should I close this issue?

Hey @kflash <https://github.com/kflash>! I'm glad you adopted the
babel-library-boilerplate and modified it into your own thing, but it's an
MIT licensed project, so you'll at least need to include a copy of the
original license here
<https://github.com/babel/babel-library-boilerplate/blob/master/LICENSE>!
Thanks!

—
Reply to this email directly or view it on GitHub
<https://github.com/Kflash/ES2015/issues/1>.

**Comment by jmeas** [comment]
I'm just saying it's clear that you copy + pasted huge pieces of my project when you made this one. The MIT states that modifications are fine and dandy so long as the license remains in the new project.

If you don't choose to, then that's fine, I guess, but it's kinda lame :stuck_out_tongue:

**Comment by Kflash** [comment]
Point me to anything else then thos 12 lines of code I copied regarding the
estrato umd. You have to subtract gulp-header and Travis process in same
code piece

**Comment by Kflash** [comment]
@jmeas I'm not here for discussion. So we do this simple. I don't need this boilerplate either, I have what I have in my ongoing projects. So this will disapear in a few sec...
